export const types = {
  LOGIN: '[AUTH] login',
  LOGOUT: '[AUTH] logout',
  UI_SET_ERROR: '[UI] Set Error',
  UI_REMOVE_ERROR: '[UI] Remove Error',
  UI_START_LOADING: '[UI] Start Loading',
  UI_FINISH_LOADING: '[UI] Finish Loading',
  NOTES_ADD_NEW: '[Notes] New note',
  NOTES_ACTIVE: '[Notes] Set active note',
  NOTES_LOAD: '[Notes] Load notes',
  NOTES_UPDATED: '[Notes] Update note',
  NOTES_IMG_URL: '[Notes] Upload image',
  NOTES_DELETE: '[Notes] Delete note',
  NOTES_LOGOUT_CLEANING: '[Notes] Logout cleaning',
}
